### ISSUE TITLE
"Could not start Xvfb" - windows 10

### ISSUE THREAD

**Issue by siraajahmed** [Rob--W/node-xvfb#10]
Hi

I am running it on windows, and it wont start. I think this is because it can't create the lockfile.
Do you know a quick way around this?
I'm using the synchronous functions with protractor js.

Also worth noting I'll only be running 1 instance of this at a time so I dont think I need the lockfile part.

Thanks

**Comment by Rob--W** [comment]
This library relies on `Xvfb`, which is not supported on Windows.

Try an alternative, e.g. mentioned at https://stackoverflow.com/questions/944086/is-there-anything-like-xvfb-or-xnest-for-windows
