### ISSUE TITLE
Cannot set displayNum: 0

### ISSUE THREAD

**Issue by 0x41mmarVM** [Rob--W/node-xvfb#11]
Title says it all. Constructor option displayNum is not taken into account if value is set to 0.

**Comment by Rob--W** [comment]
Try passing the value as a string instead of a number, i.e. `displayNum: "0"` instead of `displayNum: 0`

**Comment by 0x41mmarVM** [comment]
Shockingly, that worked. Thanks for that.
So `"0"==true` evaluates to `false` but ` "0" ? true:false` evaluates to `true`. Ah Javascript, you crack me up.

**Comment by Rob--W** [comment]
In case you're interested:

`"0"` is a non-empty string, so it is truthy - https://developer.mozilla.org/en-US/docs/Glossary/Truthy

`0` is falsey by definition - https://developer.mozilla.org/en-US/docs/Glossary/Falsy

**Comment by Rob--W** [comment]
Published 0.4.0 with your PR.
