### ISSUE TITLE
'str::runtime_error' after several week of using library on production env

### ISSUE THREAD

**Issue by qubiack** [Rob--W/node-xvfb#13]
I used this library inside a docker container for several weeks and everything was OK until today. Now when my service try to initialize an XVFB I got an error like this, server is restarted and it's happening again:

```
Listening on port 3200...

terminate called after throwing an instance of 'std::runtime_error'
  what():  eglInitialize() failed.

Listening on port 3200...
```

I need to rebuild my container and after this operation, the container starts working again, and this error doesn't appear.

I use node-xvfb in version 0.3.0

**Comment by Rob--W** [comment]
I'm afraid that I cannot help you with this issue. You'll probably encounter the same issue if you use `xvfb-run` or `Xvfb` directly, instead of node-xvfb (which really is just a wrapper around `Xvfb`).

**Comment by qubiack** [comment]
Yes - I test it with XVFB directly and I have the same problem before rebuild container. But do you have any idea what causes this problem if you aware of this?

**Comment by Rob--W** [comment]
I have no idea, there is not enough information to debug it. I would check whether the issue is specific to your application, whether the X server is still running, and/or whether the X server has run out of available clients.

**Comment by qubiack** [comment]
@Rob--W  I have this issue from time to time but recently I have it every few hours;/  Do you have any idea how could I try to restart this XVFB just from bash etc? Some kind of rescue command that could be trigger before I start my Node application? Right now when the application is failed, the container restart this process but XVFB is still not working. So this simple solution would be helpful for me.

**Comment by Rob--W** [comment]
I don't know what's happening, so I don't know how to rescue from this either. If you do figure it our, please post here in case others encounter the same issue.

**Comment by krzysztofKubiakVizlib** [comment]
I don't solve this issue but it's connected probably with server resources enabled in specific moment. When I just start restart whole docker container everyday problem is not visible.

**Comment by qubiack** [comment]
@Rob--W did you notice some changes in Xvfb on a Linux machine that cause some issues with your library? When I create a new container from scratches it's don't work and always return an error: 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  eglInitialize() failed.
```
I build previously many containers in the same base code - I try even move back into some releases from December but now always I have the same problem. I suppose it's connected with Docker Environemnet so with Ubuntu 20.04 and `xvfb` installed inside a container ;/

**Comment by Rob--W** [comment]
I don't, but I haven't directly used this library, so it could be that I missed something.
