### ISSUE TITLE
Question about running multiple displays in same process

### ISSUE THREAD

**Issue by delimmy** [Rob--W/node-xvfb#15]
Hi,

Thanks for the useful package. I had a question about this use case:

Is it possible to use multiple different displays in the same node process? My understanding is each time we call startSync(), it spawns a Xvfb process and sets the parent process DISPLAY env var to the new display num. I think this means all the code in the parent process will start using the most recently spawned Xvfb process display right, even if a function called startSync() before to create another display?

Is there a way to create isolation so I can use different displays in the same node process? e.g.
```
async function a() {
  xvfb.startSync();
  
  // code that uses the virtual frame buffer here
  
  xvfb.stopSync();
}
// note: executed in parallel
await Promise.all([
  a() // uses display 1
  a() // uses display 2
]);
```

**Comment by Rob--W** [comment]
You can read the value of `process.env.DISPLAY` before calling `startSync` / `start`, and set that environment variable when you start a new process with a specific display.

**Comment by delimmy** [comment]
Do you mean after `startSync`, something like this?
```
async function a() {
  xvfb.startSync();

  const currDisplay = process.env.DISPLAY;
  // spawn new process with env var DISPLAY=${currDisplay}
  
  xvfb.stopSync();
}
// note: executed in parallel
await Promise.all([
  a() // uses display 1
  a() // uses display 2
]);
```

**Comment by Rob--W** [comment]
Yes. But note that stopSync kills the display.

If you want to use multiple in parallel, use `start`/`stop` instead of startSync/stopSync.

**Comment by delimmy** [comment]
Got it. Much thanks for the help and quick responses.

**Comment by vayaszsolt** [comment]
@Rob--W @delimmy I am using Jenkins to start/stop xvfb. Is there an xvfb option to start the xvfb in sync mode? I ask this because I run tests in parallel on the same node.
