### ISSUE TITLE
XIO:  fatal IO error 0 (No error information) on X server ":9"

### ISSUE THREAD

**Issue by lanceschi** [Rob--W/node-xvfb#8]
Hi @Rob--W ,

do you have any clue regarding this error? First run work flawlessly then the second function call regularly prints out the below error.

```bash
XIO:  fatal IO error 0 (No error information) on X server ":9"
      after 60 requests (60 known processed) with 0 events remaining.
```

Source javascript code:
```javascript
  const Xvfb = require('xvfb');
  const xvfb = new Xvfb({
    displayNum: 9,
    reuse: false,
  });

  xvfb.startSync();

  ...

  xvfb.stopSync();

```

Thanks in advance

**Comment by lanceschi** [comment]
If I don't set any property when I'm creating a new instance of Xvfb, I'm getting this error:

```bash
XIO:  fatal IO error 0 (No error information) on X server ":99"
      after 60 requests (60 known processed) with 0 events remaining.
```

Additional warning:
```bash
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
```

**Comment by Rob--W** [comment]
Can't reproduce, and the error message in this report is of no use to me.

Have you confirmed that the issue is caused by this library, instead of whatever you do between `xvfb.startSync` and `xvfb.stopSync`?

**Comment by lanceschi** [comment]
Hi @Rob--W , thanks for reaching out, most probably you're right. Closing this.
